# BMad Unity Game Development Expansion Pack Configuration
# This configuration file defines all settings for the Unity game development expansion pack

# Basic Expansion Pack Metadata
name: bmad-unity-game-dev
version: 1.5.0
short-title: Unity C# Game Dev Pack
description: >-
  Unity Game Development expansion pack for BMad Framework. 
  Provides specialized agents, workflows, and templates for Unity game development.
  Supports both 2D and 3D game development with optional enterprise automation features.
  Default installation provides complete Unity development capabilities with manual validation.
  Optional enterprise features include automated testing, performance monitoring, and CI/CD templates.
author: pbean (PinkyD)
slashPrefix: BMadU

# Core Configuration Settings
# These settings control how the expansion pack integrates with the BMad framework

# Markdown Processing
markdownExploder: true

# Product Requirements Document (PRD) Configuration
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md

# Architecture Documentation Configuration
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture

# Game-Specific Document Configuration
gdd:
  gddVersion: v4
  gddSharded: true
  gddLocation: docs/game-design-doc.md
  gddShardedLocation: docs/gdd
  epicFilePattern: epic-{n}*.md

gamearchitecture:
  gamearchitectureFile: docs/architecture.md
  gamearchitectureVersion: v3
  gamearchitectureLocation: docs/game-architecture.md
  gamearchitectureSharded: true
  gamearchitectureShardedLocation: docs/game-architecture

# Game Development Document Locations
gamebriefdocLocation: docs/game-brief.md
levelDesignLocation: docs/level-design.md

# Unity-Specific Configuration
# Default game dimension - can be overridden per project
gameDimension: 2D

# Development Tools Configuration
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories

# Always-loaded files for development context
# These files provide essential Unity context for all agents
devLoadAlwaysFiles:
  - docs/game-architecture/9-coding-standards.md
  - docs/game-architecture/3-tech-stack.md
  - docs/game-architecture/8-unity-project-structure.md

# Custom technical documents (null = use defaults)
customTechnicalDocuments: null

# Optional Enterprise Features Configuration
# Set enterpriseFeatures.enabled: true to activate advanced automation capabilities
enterpriseFeatures:
  enabled: false  # Set to true to enable advanced automation features
  profilerIntegration: false  # Unity Profiler API automation for performance monitoring
  performanceMonitoring: false  # Automated performance regression detection
  memoryLeakDetection: false  # Advanced memory leak detection and analysis
  cicdIntegration: false  # CI/CD pipeline template generation and setup

# Testing Framework Configuration  
testingFramework:
  mode: "basic"  # Options: basic (manual validation), automated (Unity Test Framework), enterprise (full automation)
  unityTestFramework: false  # Enable Unity Test Framework integration for automated testing
  automatedValidation: false  # Automated validation task execution
  performanceTesting: false  # Include performance testing in validation

# CI/CD Template Configuration (when enterpriseFeatures.cicdIntegration: true)
cicdTemplates:
  enabled: false  # Generate CI/CD pipeline templates for user implementation
  platforms: []  # Options: ["github", "azure", "gitlab"] - platforms to generate templates for
  performanceTesting: false  # Include performance testing stages in CI/CD templates
  multiPlatform: false  # Include multi-platform build matrices (Windows, Android, iOS, WebGL)

# Unity Editor Configuration
# Path to Unity Editor executable (optional - system PATH will be used if not specified)
unityEditorLocation: null
