name: bmad-unity-game-dev
version: 1.5.0
short-title: Unity C# Game Dev Pack
description: Game Development expansion pack for BMad Method - Unity & C# focused (2D and 3D)
author: pbean (PinkyD)
slashPrefix: bmadu
