name: "BMad Code Review"
description: "Trigger BMad QA agent review when code files are saved"
trigger:
  type: "file_save"
  pattern: "src/**/*.{ts,tsx,js,jsx}"
  debounce: 2000
action:
  agent: "bmad-qa"
  task: "review-code-changes"
  context:
    - "#File"
    - "#Git Diff"
    - "#Problems"
    - "#Terminal"
parameters:
  review_scope: "changed_files"
  include_tests: true
  security_check: true
  performance_analysis: true
  auto_fix_suggestions: true