name: "BMad Story Progression"
description: "Automatically progress to next development story when current tasks are completed"
trigger:
  type: "file_change"
  pattern: ".kiro/specs/task-management/tasks.md"
  condition: "task_completed"
action:
  agent: "bmad-scrum-master"
  task: "create-next-story"
  context:
    - "#File"
    - "#Git Diff"
    - "#Codebase"
parameters:
  auto_advance: true
  notification_channels:
    - "slack"
    - "email"
  validation_required: false